### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by tuzzo77** [Boris-Em/ARCharts#34]
![schermata 2017-08-24 alle 10 07 11](https://user-images.githubusercontent.com/4814593/29656201-0a8979ae-88b4-11e7-8b3e-90e8e6971542.png)

**Comment by Boris-Em** [comment]
Thank you for reporting this bug @tuzzo77!
Could you please test #35 to make sure that it's fixed for you?

**Comment by tuzzo77** [comment]
My class stopPulsing (downloaded from the zip) is different from yours....in #35 

![schermata 2017-08-25 alle 14 37 45](https://user-images.githubusercontent.com/4814593/29714320-fd84304c-89a2-11e7-8c89-7e5df99c4e45.png)

**Comment by Boris-Em** [comment]
Did you make this modification yourself @tuzzo77?
I just merged #35, which fixes the compilation issues with XCode Beta 6.
